language: python

python:
  - "3.5"

install: 
  - "pip install -r requirements_dev.txt"

script:
  - "DJANGO_SETTINGS_MODULE=cove_project.settings python -m pytest cove_bods/tests.py"
  - "flake8 cove_project/ cove_bods/"
